<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>gni</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^def\s+[^:]*:\s*$</string>
	<key>foldingStopMarker</key>
	<string>^\s*$</string>
	<key>name</key>
	<string>gnirut</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.gnirut</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.label</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(letters) (([.a-zA-Z0-9_'']+,)*[.a-zA-Z0-9_'']+).</string>
			<key>name</key>
			<string>gnirut.letters</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(def|fun|from|call|letters|but|write|else)\b|\&lt;-|-\&gt;|\|</string>
			<key>name</key>
			<string>keyword.control.gnirut</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*[.a-zA-Z0-9_']*\. </string>
			<key>name</key>
			<string>constant.label</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#.*$\n?</string>
			<key>name</key>
			<string>comment.line.gnirut</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.label</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.label</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([.a-zA-Z0-9_'']*):([.a-zA-Z0-9_'']*)</string>
			<key>name</key>
			<string>gnirut.matching</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.other.operator</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\[|\&lt;)\s*[.a-zA-Z0-9_'',]*\s*(\|)\s*([.a-zA-Z]*\s+)?(([.a-zA-Z0-9_'']+\s*)*)(\|)\s*[.a-zA-Z0-9_'',]*\s*(\&gt;|\])</string>
			<key>name</key>
			<string>gnirut.pattern</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.gnirut</string>
	<key>uuid</key>
	<string>C07519D5-8FB6-4F31-8C38-B39E2C22FB2E</string>
</dict>
</plist>
